services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan migrate --force
      php artisan db:seed --force
      php artisan config:clear
      php artisan config:cache
      php artisan storage:link
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
